import React, { useState } from 'react';
import { Box, Container, Typography, TextField, Button, Card, CardContent, Tabs, Tab, useTheme } from '@mui/material';
import CodeIcon from '@mui/icons-material/Code';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';

const AIChatDemo = () => {
  const theme = useTheme();
  const [activeTab, setActiveTab] = useState(0);
  const [prompt, setPrompt] = useState('');
  const [generatedCode, setGeneratedCode] = useState(''); // Mock generated code
  
  const handleGenerate = () => {
    // Mock code generation
    const mockCode = `// Generated by ColaJS AI
function fibonacci(n) {
  if (n <= 1) return n;
  return fibonacci(n - 1) + fibonacci(n - 2);
}

// Usage
console.log(fibonacci(${prompt || 10}));`;
    setGeneratedCode(mockCode);
  };

  const handleTabChange = (event, newValue) => {
    setActiveTab(newValue);
  };

  return (
    <Box sx={{ py: 4 }}>
      <Tabs 
        value={activeTab} 
        onChange={handleTabChange} 
        centered
        sx={{ mb: 4 }}
      >
        <Tab icon={<CodeIcon />} label="AI代码生成" />
        <Tab icon={<AutoAwesomeIcon />} label="智能对话" />
      </Tabs>
      
      {activeTab === 0 && (
        <Card sx={{ p: 3 }}>
          <Typography variant="h5" sx={{ mb: 3, fontWeight: 600 }}>
            AI代码生成演示
          </Typography>
          <TextField
            fullWidth
            multiline
            rows={4}
            placeholder="请输入您的需求，例如：'创建一个计算斐波那契数列的函数'"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            sx={{ mb: 3 }}
          />
          <Button
            variant="contained"
            onClick={handleGenerate}
            sx={{ 
              background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
              '&:hover': {
                background: 'linear-gradient(135deg, #5a6fd8 0%, #6a4292 100%)',
              }
            }}
          >
            生成代码
          </Button>
          
          {generatedCode && (
            <Box sx={{ mt: 4 }}>
              <Typography variant="h6" sx={{ mb: 2, fontWeight: 600 }}>
                生成的代码：
              </Typography>
              <Card sx={{ 
                p: 2, 
                background: '#f5f5f5', 
                fontFamily: 'monospace',
                overflowX: 'auto'
              }}>
                <pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{generatedCode}</pre>
              </Card>
              <Button 
                variant="outlined" 
                sx={{ mt: 2 }}
                onClick={() => navigator.clipboard.writeText(generatedCode)}
              >
                复制代码
              </Button>
            </Box>
          )}
        </Card>
      )}
      
      {activeTab === 1 && (
        <Card sx={{ p: 3 }}>
          <Typography variant="h5" sx={{ mb: 3, fontWeight: 600 }}>
            智能对话演示
          </Typography>
          <Box sx={{ 
            height: 300, 
            border: '1px solid #e0e0e0', 
            borderRadius: 2, 
            p: 2,
            mb: 2,
            overflowY: 'auto',
            background: '#f9f9f9'
          }}>
            <Box sx={{ mb: 2 }}>
              <Typography sx={{ fontWeight: 600, color: '#2196F3' }}>用户：</Typography>
              <Typography>如何优化React应用的性能？</Typography>
            </Box>
            <Box sx={{ mb: 2 }}>
              <Typography sx={{ fontWeight: 600, color: '#00BCD4' }}>ColaJS AI：</Typography>
              <Typography>
                优化React应用性能的关键策略包括：
                1. 使用React.memo避免不必要的重渲染
                2. 使用useCallback和useMemo缓存函数和计算结果
                3. 实现代码分割和懒加载
                4. 优化列表渲染，使用虚拟滚动
                5. 避免在渲染函数中创建新对象
              </Typography>
            </Box>
          </Box>
          <TextField
            fullWidth
            placeholder="输入您的问题..."
            disabled
            helperText="这是一个演示，实际功能需要后端支持"
          />
        </Card>
      )}
    </Box>
  );
};

export default AIChatDemo;