import React from 'react';

const Demo = () => {
  const [activeTab, setActiveTab] = React.useState(0);
  const [prompt, setPrompt] = React.useState('');
  const [generatedCode, setGeneratedCode] = React.useState('');

  const handleGenerate = () => {
    const mockCode = `// Generated by ColaJS AI
function fibonacci(n) {
  if (n <= 1) return n;
  return fibonacci(n - 1) + fibonacci(n - 2);
}

// Usage
console.log(fibonacci(${prompt || 10}));`;

    setGeneratedCode(mockCode);
  };

  const tabs = [
    { icon: '💻', label: 'AI代码生成' },
    { icon: '💬', label: '智能对话' },
  ];

  return (
    <div className="page-content">
      <h1 className="page-title">功能演示</h1>
      <p className="page-subtitle">
        体验ColaJS的AI全栈开发能力，包括智能代码生成、对话系统和API集成等功能。
      </p>

      <div style={{ background: '#fff', borderRadius: '24px', padding: '40px', boxShadow: 'var(--shadow-md)', marginBottom: '48px' }}>
        <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '40px' }}>
          {tabs.map((tab, index) => (
            <button
              key={index}
              onClick={() => setActiveTab(index)}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '12px',
                padding: '16px 32px',
                fontSize: '1.1rem',
                fontWeight: '600',
                background: activeTab === index ? 'var(--primary-gradient)' : 'rgba(102, 126, 234, 0.1)',
                color: activeTab === index ? '#fff' : '#666',
                borderRadius: '50px',
                border: 'none',
                cursor: 'pointer',
                transition: 'all 0.3s',
              }}
            >
              {tab.icon} {tab.label}
            </button>
          ))}
        </div>

        {activeTab === 0 && (
          <div style={{ maxWidth: '800px', margin: '0 auto' }}>
            <h2 style={{ fontSize: '1.75rem', fontWeight: '700', marginBottom: '24px', color: '#333' }}>
              AI代码生成演示
            </h2>

            <textarea
              rows={4}
              placeholder="请输入您的需求，例如：'创建一个计算斐波那契数列的函数'"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              style={{
                width: '100%',
                padding: '16px',
                borderRadius: '16px',
                border: '2px solid rgba(102, 126, 234, 0.2)',
                fontSize: '1rem',
                resize: 'vertical',
                marginBottom: '24px',
                fontFamily: '"Fira Code", "Courier New", monospace',
              }}
            />

            <button
              onClick={handleGenerate}
              style={{
                padding: '14px 40px',
                fontSize: '1.1rem',
                fontWeight: '700',
                background: 'var(--primary-gradient)',
                color: '#fff',
                border: 'none',
                borderRadius: '50px',
                cursor: 'pointer',
                transition: 'all 0.3s',
              }}
            >
              生成代码
            </button>

            {generatedCode && (
              <div style={{ marginTop: '48px' }}>
                <h3 style={{ fontSize: '1.5rem', fontWeight: '700', marginBottom: '24px', color: '#333' }}>
                  生成的代码：
                </h3>

                <div style={{
                  background: 'linear-gradient(135deg, #1e1e2e 0%, #2d2d44 100%)',
                  borderRadius: '16px',
                  padding: '32px',
                  fontFamily: '"Fira Code", "Courier New", monospace',
                  color: '#e0e0e0',
                  overflowX: 'auto',
                  marginBottom: '24px',
                }}>
                  <pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{generatedCode}</pre>
                </div>

                <button
                  onClick={() => navigator.clipboard.writeText(generatedCode)}
                  style={{
                    padding: '12px 32px',
                    fontSize: '1rem',
                    fontWeight: '600',
                    background: 'rgba(102, 126, 234, 0.1)',
                    color: '#667eea',
                    border: '2px solid var(--primary-gradient)',
                    borderRadius: '50px',
                    cursor: 'pointer',
                    transition: 'all 0.3s',
                  }}
                >
                  复制代码
                </button>
              </div>
            )}
          </div>
        )}

        {activeTab === 1 && (
          <div style={{ maxWidth: '800px', margin: '0 auto' }}>
            <h2 style={{ fontSize: '1.75rem', fontWeight: '700', marginBottom: '24px', color: '#333' }}>
              智能对话演示
            </h2>

            <div style={{
              height: '400px',
              border: '2px solid rgba(102, 126, 234, 0.2)',
              borderRadius: '16px',
              padding: '24px',
              overflowY: 'auto',
              background: 'rgba(248, 249, 250, 0.5)',
              marginBottom: '24px',
            }}>
              <div style={{ marginBottom: '24px' }}>
                <strong style={{ color: '#667eea' }}>用户：</strong>
                <div style={{ marginLeft: '40px', color: '#333' }}>如何优化React应用的性能？</div>
              </div>
              <div style={{ marginBottom: '24px' }}>
                <strong style={{ color: '#11998e' }}>ColaJS AI：</strong>
                <div style={{ marginLeft: '40px', color: '#333', lineHeight: 1.8 }}>
                  优化React应用性能的关键策略包括：
                  <br />
                  1. 使用React.memo避免不必要的重渲染
                  <br />
                  2. 使用useCallback和useMemo缓存函数和计算结果
                  <br />
                  3. 实现代码分割和懒加载
                  <br />
                  4. 优化列表渲染，使用虚拟滚动
                  <br />
                  5. 避免在渲染函数中创建新对象
                </div>
              </div>
            </div>

            <div>
              <input
                type="text"
                placeholder="输入您的问题..."
                disabled
                style={{
                  width: '100%',
                  padding: '14px 20px',
                  borderRadius: '50px',
                  fontSize: '1rem',
                  border: '2px solid #ff4d4f',
                  backgroundColor: '#f5f5f5',
                  color: '#999',
                }}
              />
              <p style={{ textAlign: 'center', marginTop: '12px', fontSize: '0.875rem', color: '#ff4d4f' }}>
                ⚠️ 这是一个演示，实际功能需要后端支持
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default Demo;