import React from 'react';
import { Typography, Tabs, Card, Input, Button, Space } from 'antd';
import { CodeOutlined, RocketOutlined } from '@ant-design/icons';

const { Title, Text } = Typography;
const { TextArea } = Input;

const Demo = () => {
  const [activeTab, setActiveTab] = React.useState('1');
  const [prompt, setPrompt] = React.useState('');
  const [generatedCode, setGeneratedCode] = React.useState('');

  const handleGenerate = () => {
    const mockCode = `// Generated by ColaJS AI
function fibonacci(n) {
  if (n <= 1) return n;
  return fibonacci(n - 1) + fibonacci(n - 2);
}

// Usage
console.log(fibonacci(${prompt || 10}));`;

    setGeneratedCode(mockCode);
  };

  const items = [
    {
      key: '1',
      label: (
        <Space>
          <CodeOutlined />
          AI代码生成
        </Space>
      ),
      children: (
        <Card style={{ border: 'none', boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)' }}>
          <Title level={3} style={{ marginBottom: 24, fontWeight: 600 }}>
            AI代码生成演示
          </Title>
          <TextArea
            rows={4}
            placeholder="请输入您的需求，例如：'创建一个计算斐波那契数列的函数'"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            style={{ marginBottom: 24 }}
          />
          <Button
            type="primary"
            style={{
              background: 'linear-gradient(135deg, #1677FF 0%, #597EF7 100%)',
              border: 'none',
            }}
            onClick={handleGenerate}
          >
            生成代码
          </Button>

          {generatedCode && (
            <div style={{ marginTop: 32 }}>
              <Title
                level={4}
                style={{
                  fontWeight: 600,
                  marginBottom: 16,
                }}
              >
                生成的代码：
              </Title>
              <Card
                style={{
                  padding: 16,
                  background: '#f5f5f5',
                  fontFamily: 'monospace',
                  overflowX: 'auto',
                  marginBottom: 16,
                }}
                bodyStyle={{ padding: 0 }}
              >
                <pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{generatedCode}</pre>
              </Card>
              <Button
                type="default"
                onClick={() => navigator.clipboard.writeText(generatedCode)}
              >
                复制代码
              </Button>
            </div>
          )}
        </Card>
      ),
    },
    {
      key: '2',
      label: (
        <Space>
          <RocketOutlined />
          智能对话
        </Space>
      ),
      children: (
        <Card style={{ border: 'none', boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)' }}>
          <Title level={3} style={{ marginBottom: 24, fontWeight: 600 }}>
            智能对话演示
          </Title>
          <div
            style={{
              height: 300,
              border: '1px solid #d9d9d9',
              borderRadius: 6,
              padding: 16,
              marginBottom: 16,
              overflowY: 'auto',
              background: '#fafafa',
            }}
          >
            <div style={{ marginBottom: 16 }}>
              <Text strong style={{ color: '#1677FF' }}>用户：</Text>
              <Text style={{ display: 'block', marginLeft: 48 }}>如何优化React应用的性能？</Text>
            </div>
            <div style={{ marginBottom: 16 }}>
              <Text strong style={{ color: '#13C2C2' }}>ColaJS AI：</Text>
              <Text style={{ display: 'block', marginLeft: 48 }}>
                优化React应用性能的关键策略包括：
                <br />
                1. 使用React.memo避免不必要的重渲染
                <br />
                2. 使用useCallback和useMemo缓存函数和计算结果
                <br />
                3. 实现代码分割和懒加载
                <br />
                4. 优化列表渲染，使用虚拟滚动
                <br />
                5. 避免在渲染函数中创建新对象
              </Text>
            </div>
          </div>
          <Input
            placeholder="输入您的问题..."
            disabled
            status="error"
            suffix={<span style={{ color: '#FF4D4F' }}>演示模式</span>}
          />
          <Text type="secondary" style={{ display: 'block', marginTop: 8, fontSize: 12 }}>
            这是一个演示，实际功能需要后端支持
          </Text>
        </Card>
      ),
    },
  ];

  return (
    <div style={{ padding: '80px 0' }}>
      <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px' }}>
        <Title
          style={{
            marginBottom: 48,
            fontWeight: 600,
            textAlign: 'center',
          }}
        >
          功能演示
        </Title>

        <Text
          style={{
            display: 'block',
            marginBottom: 48,
            textAlign: 'center',
            maxWidth: 600,
            margin: '0 auto 48px auto',
            color: '#666666',
          }}
        >
          体验ColaJS的AI全栈开发能力，包括智能代码生成、对话系统和API集成等功能。
        </Text>

        <Tabs defaultActiveKey="1" items={items} style={{ maxWidth: 800, margin: '0 auto' }} />
      </div>
    </div>
  );
};

export default Demo;